// <auto-generated />
namespace ASP_IDENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatearticles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatearticles));
        
        string IMigrationMetadata.Id
        {
            get { return "202201172100545_updatearticles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
